// sections/OverviewPanel.tsx

import CategoryCard from '@/features/inventory/components/ui/card/CategoryCard';
import { categories } from '@/features/inventory/constants/categories';
import { autoGeneratedLayout } from '@/shared/utils/layout/layoutAutoGenerated';

const DynamicGridAreaStyles = () => {
  const css = categories
    .map((c) => `.grid-area-${c.id}{grid-area:${c.id};}`)
    .join('\n');

  return <style>{css}</style>;
};

const OverviewPanel: React.FC = () => {
  const layout = autoGeneratedLayout;

  const gridTemplate = layout.map((row) => `"${row.join(' ')}"`).join(' ');

  return (
    <section className="pb-25">
      <DynamicGridAreaStyles />

      <div
        className="max-w-layout-container mx-auto grid gap-3"
        style={{
          gridTemplateAreas: gridTemplate,
          gridTemplateColumns: '1fr 1fr',
          gridAutoRows: '9rem',
        }}
      >
        {categories.map((item) => (
          <div key={item.id} className={`grid-area-${item.id}`}>
            <CategoryCard
              id={item.id}
              title={item.title}
              img={item.img}
              bgColor={item.bgColor}
              boxShadow="shadow-[0_6px_14px_-2px_rgba(0,0,0,0.06)]"
            />
          </div>
        ))}
      </div>
    </section>
  );
};

export default OverviewPanel;
