// src/data/layoutAutoGenerated.ts

import type { LayoutType } from '@/modules/inventory/types/layoutTypes';
import { generateAutoLayout } from './autoLayoutEngine';

export const generateLayoutByType = (type: LayoutType) =>
  generateAutoLayout(type);

export const getDefaultLayout = () => generateAutoLayout('layout-a');

