/// <reference lib="webworker" />
import { cleanupOutdatedCaches, precacheAndRoute } from 'workbox-precaching';
import { clientsClaim } from 'workbox-core';
import { initializeApp } from 'firebase/app';
import { getMessaging, onBackgroundMessage } from 'firebase/messaging/sw';

declare let self: ServiceWorkerGlobalScope;

cleanupOutdatedCaches();

// Precache all assets generated by your build process.
// Their URLs are injected into the manifest variable below.
// This variable must be present somewhere in your service worker file,
// even if you decide not to use precaching. See https://vite-pwa-org.netlify.app/guide/inject-manifest.html
precacheAndRoute(self.__WB_MANIFEST);

self.skipWaiting();
clientsClaim();

const firebaseConfig = {
  apiKey: import.meta.env.VITE_FIREBASE_API_KEY,
  authDomain: import.meta.env.VITE_FIREBASE_AUTH_DOMAIN,
  projectId: import.meta.env.VITE_FIREBASE_PROJECT_ID,
  storageBucket: import.meta.env.VITE_FIREBASE_STORAGE_BUCKET,
  messagingSenderId: import.meta.env.VITE_FIREBASE_MESSAGING_SENDER_ID,
  appId: import.meta.env.VITE_FIREBASE_APP_ID,
};

// Initialize Firebase
try {
  // Only initialize if config is present (basic check)
  if (firebaseConfig.apiKey) {
    const app = initializeApp(firebaseConfig);
    const messaging = getMessaging(app);

    onBackgroundMessage(messaging, (payload) => {
      console.log('[sw] Received background message ', payload);
      const notificationTitle =
        payload.notification?.title || 'Fufood Notification';
      const notificationOptions = {
        body: payload.notification?.body,
        icon: '/pwa-192x192.png',
        data: payload.data,
      };

      self.registration.showNotification(
        notificationTitle,
        notificationOptions,
      );
    });
    console.log('[sw] Firebase Messaging Initialized');
  }
} catch (err) {
  console.error('[sw] Firebase Initialization Error:', err);
}
