import { useEffect, useState } from 'react';
import { useSelector, useDispatch } from 'react-redux';
import { setLayout } from '@/modules/inventory/store/inventorySlice';
import CategoryCard from '@/modules/inventory/components/ui/card/CategoryCard';
import { generateLayoutByType } from '@/shared/utils/layout/layoutAutoGenerated';
import { inventoryApi } from '@/modules/inventory/api';
import ChangeLayoutButton from '@/modules/inventory/components/ui/other/ChangeLayoutButton';
import { selectCurrentLayout } from '@/modules/inventory/store/inventorySlice';
import type { CategoryInfo } from '@/modules/inventory/types';

const DynamicGridAreaStyles = ({
  categories,
}: {
  categories: CategoryInfo[];
}) => {
  const css = categories
    .map((c) => `.grid-area-${c.id}{grid-area:${c.id};}`)
    .join('\n');

  return <style>{css}</style>;
};

const OverviewPanel: React.FC = () => {
  const [categories, setCategories] = useState<CategoryInfo[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const currentLayout = useSelector(selectCurrentLayout);
  const dispatch = useDispatch();

  useEffect(() => {
    const fetchCategories = async () => {
      try {
        const response = await inventoryApi.getCategories();
        setCategories(response.data.categories);
      } catch (error) {
        console.error('Failed to fetch categories:', error);
      } finally {
        setIsLoading(false);
      }
    };

    const fetchSettings = async () => {
      try {
        const response = await inventoryApi.getSettings();
        if (response.data.settings.layoutType) {
          dispatch(setLayout(response.data.settings.layoutType));
        }
      } catch (error) {
        console.error('Failed to fetch settings:', error);
      }
    };

    fetchCategories();
    fetchSettings();
  }, [dispatch]);

  const layout = generateLayoutByType(currentLayout);
  const gridTemplate = layout.map((row) => `"${row.join(' ')}"`).join(' ');

  if (isLoading) {
    return <div className="p-4 text-center">Loading categories...</div>;
  }

  return (
    <section className="pb-25 relative">
      <DynamicGridAreaStyles categories={categories} />

      <div
        className="max-w-layout-container mx-auto grid gap-3 mb-10"
        style={{
          gridTemplateAreas: gridTemplate,
          gridTemplateColumns: '1fr 1fr',
          gridAutoRows: '9rem',
        }}
      >
        {categories.map((item) => (
          <div key={item.id} className={`grid-area-${item.id}`}>
            <CategoryCard
              id={item.id}
              title={`${item.title} | ${item.count}`}
              img={item.imageUrl}
              bgColor={item.bgColor}
              boxShadow="shadow-[0_6px_14px_-2px_rgba(0,0,0,0.06)]"
            />
          </div>
        ))}
      </div>

      <ChangeLayoutButton />
    </section>
  );
};

export default OverviewPanel;
