import { useEffect, useState, useMemo } from 'react';
import { useSelector, useDispatch } from 'react-redux';
import {
  setLayout,
  setCategoryOrder,
  setSettings,
} from '@/modules/inventory/store/inventorySlice';
import CategoryCard from '@/modules/inventory/components/ui/card/CategoryCard';
import { generateLayoutByType } from '@/shared/utils/layout/layoutAutoGenerated';
import { inventoryApi } from '@/modules/inventory/api';
import ChangeLayoutButton from '@/modules/inventory/components/ui/other/ChangeLayoutButton';
import {
  selectCurrentLayout,
  selectCategoryOrder,
} from '@/modules/inventory/store/inventorySlice';
import useFadeInAnimation from '@/shared/hooks/useFadeInAnimation';
import type { CategoryInfo } from '@/modules/inventory/types';

const DynamicGridAreaStyles = ({
  categories,
}: {
  categories: CategoryInfo[];
}) => {
  const css = categories
    .map((c) => `.grid-area-${c.id}{grid-area:${c.id};}`)
    .join('\n');

  return <style>{css}</style>;
};

const OverviewPanel: React.FC = () => {
  const [categories, setCategories] = useState<CategoryInfo[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const { ref: contentRef } = useFadeInAnimation<HTMLElement>({ isLoading });
  const currentLayout = useSelector(selectCurrentLayout);
  const categoryOrder = useSelector(selectCategoryOrder);
  const dispatch = useDispatch();

  // 初次載入時從 API 取得資料
  useEffect(() => {
    const fetchData = async () => {
      try {
        setIsLoading(true);

        // 同時載入設定和類別
        const [settingsResponse, categoriesResponse] = await Promise.all([
          inventoryApi.getSettings(),
          inventoryApi.getCategories(),
        ]);

        // 更新設定到 Redux
        dispatch(setSettings(settingsResponse.data.settings));

        // 如果設定中有 layoutType，更新 layout
        if (settingsResponse.data.settings.layoutType) {
          dispatch(setLayout(settingsResponse.data.settings.layoutType));
        }

        // 如果設定中有 categoryOrder，更新順序
        if (settingsResponse.data.settings.categoryOrder) {
          dispatch(
            setCategoryOrder(settingsResponse.data.settings.categoryOrder),
          );
        } else {
          // 如果沒有設定順序，使用 API 回傳的預設順序
          const defaultOrder = categoriesResponse.data.categories.map(
            (c) => c.id,
          );
          dispatch(setCategoryOrder(defaultOrder));
        }

        // 設定原始類別資料
        setCategories(categoriesResponse.data.categories);
      } catch (error) {
        console.error('Failed to fetch data:', error);
      } finally {
        setIsLoading(false);
      }
    };

    fetchData();
  }, [dispatch]);

  // 根據 Redux 的 categoryOrder 排序類別（這會在 categoryOrder 變化時自動更新）
  const sortedCategories = useMemo(() => {
    if (categories.length === 0) {
      return [];
    }

    if (!categoryOrder || categoryOrder.length === 0) {
      return categories;
    }

    const ordered: CategoryInfo[] = [];

    // 按照 categoryOrder 順序添加類別
    categoryOrder.forEach((id) => {
      const category = categories.find((c) => c.id === id);
      if (category) {
        ordered.push(category);
      }
    });

    // 添加不在 categoryOrder 中的類別（如果有新類別）
    categories.forEach((category) => {
      if (!categoryOrder.includes(category.id)) {
        ordered.push(category);
      }
    });

    return ordered;
  }, [categories, categoryOrder]);

  // 使用原始版面佈局（保持不變）
  const layout = generateLayoutByType(currentLayout);
  const gridTemplate = layout.map((row) => `"${row.join(' ')}"`).join(' ');

  // 從版面中提取格子順序（不重複的類別 ID）
  const layoutSlots = useMemo(() => {
    const slots: string[] = [];
    layout.forEach((row) => {
      row.forEach((cell) => {
        if (cell && !slots.includes(cell)) {
          slots.push(cell);
        }
      });
    });
    return slots;
  }, [layout]);

  // 建立「版面格子 ID → 實際顯示的類別」的映射
  // 例如：layout 格子 0 對應 sortedCategories[0]
  const slotToCategoryMap = useMemo(() => {
    const map: Record<string, CategoryInfo | undefined> = {};
    layoutSlots.forEach((slotId, index) => {
      // 將第 index 個格子對應到排序後的第 index 個類別
      map[slotId] = sortedCategories[index];
    });
    return map;
  }, [layoutSlots, sortedCategories]);

  if (isLoading) {
    return (
      <div className="p-4 text-center text-neutral-400">
        Loading categories...
      </div>
    );
  }

  return (
    <section ref={contentRef} className="pb-30 relative">
      <DynamicGridAreaStyles categories={categories} />

      <div
        className="max-w-layout-container mx-auto grid gap-3 mb-6"
        style={{
          gridTemplateAreas: gridTemplate,
          gridTemplateColumns: '1fr 1fr',
          gridAutoRows: '9rem',
        }}
      >
        {/* 按照版面格子順序渲染，但顯示排序後的類別內容 */}
        {layoutSlots.map((slotId) => {
          const category = slotToCategoryMap[slotId];
          if (!category) return null;

          return (
            <div key={slotId} className={`grid-area-${slotId}`}>
              <CategoryCard
                id={category.id}
                title={`${category.title} | ${category.count}`}
                img={category.imageUrl}
                bgColor={category.bgColor}
                boxShadow="shadow-[0_6px_14px_-2px_rgba(0,0,0,0.06)]"
              />
            </div>
          );
        })}
      </div>

      <ChangeLayoutButton />
    </section>
  );
};

export default OverviewPanel;
